### ISSUE TITLE
Question about parseMethodCallExpression function

### ISSUE THREAD

**Issue by haifenghuang** [mayoms/monkey#12]
In `parser/calls.go` file, `parseMethodCallExpression` is as below:
```go
func (p *Parser) parseMethodCallExpression(obj ast.Expression) ast.Expression {
	methodCall := &ast.MethodCallExpression{Token: p.curToken, Object: obj}
	p.nextToken()
	name := p.parseIdentifier()
	if !p.peekTokenIs(token.LPAREN) {
		methodCall.Call = p.parseExpression(LOWEST)
	} else {
		p.nextToken()
		methodCall.Call = p.parseCallExpressions(name)
	}
	return methodCall
}
```

I'm confused by the `if` statement:
```go
if !p.peekTokenIs(token.LPAREN) {
		methodCall.Call = p.parseExpression(LOWEST)
}
```
I could not think of an usage of this example, in what situation will it go into the `methodCall.Call = p.parseExpression(LOWEST)`?
Because the source has no comment at all, Could you kindly please tell me what is the usage of this `if` statement?

**Comment by mayoms** [comment]
@haifenghuang sure - added here:

https://github.com/mayoms/monkey/commit/420f0ce4560417c662bec7937be1db3270269364

which was a subsequent commit to this one:

https://github.com/mayoms/monkey/commit/4d74acc002ac3014d3058b8d20875fe0f1dafa91

If you check out the commit initial commit where method chaining works and run the tests, you'll see that  dot-expressions that are not method calls no longer work. So for example if you have a module foo, which has a global var X, the following would fail:

```
include foo

foo.x
```

The if statement here essentially says if the next expression is not a method call expression (using peektoken to see if the identifier is followed by an `(`, call `parseExpression`, otherwise call the more specific `parseCallExpressions`. 

`parseMethodCallExpression` is probably not the best name for this method, perhaps `parseDotExpression` would work. Naming things is hard- it is on my todo to rename this to be more descriptive though.

**Comment by haifenghuang** [comment]
I see, thanks a lot for the explaining, And I will close the issue.
